default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: ".*\\.ipynb"
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements

  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=80"]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ["--line-length=80"]
      - id: black-jupyter

  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.4.0"
    hooks:
      - id: pycln
        args: ["--all"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--exclude-files", ".*\\.ipynb"]

  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.2.0
    hooks:
      - id: nb-clean
        args:
        - --remove-empty-cells
        - --preserve-cell-outputs
        - --

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
      -   id: pyupgrade
          args: [--py310-plus]
  # -   repo: https://github.com/asottile/dead
  #     rev: v1.5.2
  #     hooks:
  #     -   id: dead
